title = "Bartholomew Documentation"
base_url = "http://localhost:3000"
about = "Bartholomew — an open-source micro-CMS for hosting lightweight websites with the power of WebAssembly"

[extra]
copyright = "Fermyon"
github = "https://github.com/fermyon/bartholomew"
twitter = "https://twitter.com/fermyontech"
